---
- name: setup Lamp and install wordpress
  hosts: webserver
  gather_facts: "{{ facts }}"
  become: yes #sudo
  vars_files: vars/vars_lamp.yml
  tasks:
    - block:
        - name: install Apache
          when: ansible_facts['pkg_mgr'] == "dnf"
          dnf:
            name: "{{ apache_package_name }}"
            state: latest
        - name: start and enable apache
          when: ansible_facts['service_mgr'] == "systemd"
          systemd:
            name: "{{ apache_service_name }}"
            state: started
            enabled: yes
        - name: install PHP and Dependencies
          when: ansible_facts['pkg_mgr'] == "dnf"
          dnf:
            name: "{{ php_packages }}"
            state: latest
        - name: install wordpress
          unarchive:
            src: https://wordpress.org/latest.tar.gz
            dest: /tmp/
            remote_src: yes
        - name: copy wordpress files to /var/www/html
          copy:
            src: /tmp/wordpress/
            dest: /var/www/html/
            remote_src: yes
        - name: changing ownership of html directory
          file:
            path: /var/www/html
            state: directory
            recurse: yes
            owner: apache
            group: apache
          notify: Restart Apache  
        - name:        
      when: 
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "8"
  handlers:
    - name: Restart Apache
      when: ansible_facts['service_mgr'] == "systemd"
      systemd:
        state: restarted
        name: "{{ apache_service_name }}"
