---
- name: update all packages
  hosts: webserver, database
  become: yes
  gather_facts: yes
  tasks:
    - name: upgrade all packages
      when: ansible_facts['pkg_mgr'] == "dnf"
      dnf:
        name: '*'
        state: latest
    - name: Upgrade all packages to the latest version
      when: ansible_facts['pkg_mgr'] == "apt"
      apt:
        name: "*"
        state: latest
