---
- name: adding users
  hosts: db
  gather_facts: no
  tasks:
    - name: adding user
      user:
        name: ansible
        uid: 2500
        groups: sudo
    - name: add public key
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    